package cn.aslight.workhub.model.payment;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 项目商户绑定响应。
 */
public record PaymentProjectBindingResponse(Long id,
                                            Long projectId,
                                            String businessLineCode,
                                            String businessLine,
                                            String projectCode,
                                            String projectName,
                                            Long merchantId,
                                            String merchantCode,
                                            String merchantName,
                                            Long channelId,
                                            String channelCode,
                                            String channelName,
                                            String environment,
                                            String purposeCode,
                                            List<String> purposeCodes,
                                            Integer priority,
                                            Boolean defaultBinding,
                                            String status,
                                            String remark,
                                            List<PaymentBindingRelationResponse> relations,
                                            LocalDateTime createdAt,
                                            LocalDateTime updatedAt) {

    public PaymentProjectBindingResponse(Long id,
                                         Long projectId,
                                         String businessLine,
                                         String projectCode,
                                         String projectName,
                                         Long merchantId,
                                         String merchantCode,
                                         String merchantName,
                                         Long channelId,
                                         String channelCode,
                                         String channelName,
                                         String environment,
                                         String purposeCode,
                                         List<String> purposeCodes,
                                         Integer priority,
                                         Boolean defaultBinding,
                                         String status,
                                         String remark,
                                         List<PaymentBindingRelationResponse> relations,
                                         LocalDateTime createdAt,
                                         LocalDateTime updatedAt) {
        this(id,
                projectId,
                null,
                businessLine,
                projectCode,
                projectName,
                merchantId,
                merchantCode,
                merchantName,
                channelId,
                channelCode,
                channelName,
                environment,
                purposeCode,
                purposeCodes,
                priority,
                defaultBinding,
                status,
                remark,
                relations,
                createdAt,
                updatedAt);
    }

    public PaymentProjectBindingResponse(Long id,
                                         Long projectId,
                                         String businessLineCode,
                                         String businessLine,
                                         String projectCode,
                                         String projectName,
                                         Long merchantId,
                                         String merchantCode,
                                         String merchantName,
                                         Long channelId,
                                         String channelCode,
                                         String channelName,
                                         String environment,
                                         String purposeCode,
                                         Object purposeCodes,
                                         Integer priority,
                                         Boolean defaultBinding,
                                         String status,
                                         String remark,
                                         Object relations,
                                         LocalDateTime createdAt,
                                         LocalDateTime updatedAt) {
        this(id,
                projectId,
                businessLineCode,
                businessLine,
                projectCode,
                projectName,
                merchantId,
                merchantCode,
                merchantName,
                channelId,
                channelCode,
                channelName,
                environment,
                purposeCode,
                null,
                priority,
                defaultBinding,
                status,
                remark,
                null,
                createdAt,
                updatedAt);
    }
}
