<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
        <relativePath/>
    </parent>

    <groupId>cn.aslight</groupId>
    <artifactId>workhub-server</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>workhub-server</name>
    <description>WorkHub server parent project</description>

    <modules>
        <module>workhub-model</module>
        <module>workhub-support</module>
        <module>workhub-dao</module>
        <module>workhub-service</module>
        <module>workhub-controller</module>
        <module>workhub-job</module>
        <module>workhub-mcp-server</module>
        <module>workhub-bootstrap</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <mybatis.spring.boot.version>4.0.0</mybatis.spring.boot.version>
        <druid.version>1.2.28</druid.version>
        <jjwt.version>0.13.0</jjwt.version>
        <poi.version>5.4.1</poi.version>
        <pdfbox.version>3.0.5</pdfbox.version>
    </properties>
</project>
