package cn.aslight.workhub.model.intake;

import java.util.List;

/**
 * 研发需求代码影响分析草稿。
 */
public record DevelopmentAnalysisDraft(String status,
                                       String businessLine,
                                       Long projectId,
                                       String projectName,
                                       String repositoryUrl,
                                       String requirementRawPath,
                                       String requirementWikiPath,
                                       String requirementWikiUrl,
                                       String summary,
                                       List<String> requirementChangePoints,
                                       List<String> impactedModules,
                                       List<String> risks,
                                       List<String> questions,
                                       List<String> developerPool,
                                       List<DevelopmentWorkItemDraft> workItems,
                                       String totalEstimatedEffort,
                                       String developmentEstimatedEffort,
                                       String testingEstimatedEffort,
                                       String plannedDueDate,
                                       String plannedTestingStartDate,
                                       String plannedTestingEndDate,
                                       String plannedReleaseDate,
                                       String zentaoSyncStatus,
                                       String zentaoSyncMessage,
                                       String generatedAt,
                                       String generator,
                                       String plannedDevelopmentStartDate) {

    public DevelopmentAnalysisDraft(String status,
                                    String businessLine,
                                    Long projectId,
                                    String projectName,
                                    String repositoryUrl,
                                    String requirementRawPath,
                                    String requirementWikiPath,
                                    String requirementWikiUrl,
                                    String summary,
                                    List<String> requirementChangePoints,
                                    List<String> impactedModules,
                                    List<String> risks,
                                    List<String> questions,
                                    List<String> developerPool,
                                    List<DevelopmentWorkItemDraft> workItems,
                                    String totalEstimatedEffort,
                                    String developmentEstimatedEffort,
                                    String testingEstimatedEffort,
                                    String plannedDueDate,
                                    String plannedTestingStartDate,
                                    String plannedTestingEndDate,
                                    String plannedReleaseDate,
                                    String zentaoSyncStatus,
                                    String zentaoSyncMessage,
                                    String generatedAt,
                                    String generator) {
        this(
                status,
                businessLine,
                projectId,
                projectName,
                repositoryUrl,
                requirementRawPath,
                requirementWikiPath,
                requirementWikiUrl,
                summary,
                requirementChangePoints,
                impactedModules,
                risks,
                questions,
                developerPool,
                workItems,
                totalEstimatedEffort,
                developmentEstimatedEffort,
                testingEstimatedEffort,
                plannedDueDate,
                plannedTestingStartDate,
                plannedTestingEndDate,
                plannedReleaseDate,
                zentaoSyncStatus,
                zentaoSyncMessage,
                generatedAt,
                generator,
                null
        );
    }
}
