package cn.aslight.workhub.model.intake;

import java.time.LocalDateTime;
import java.util.List;

/**
 * IntakeSummary 响应模型。
 */
public record IntakeSummaryResponse(Long id,
                                    String sourceType,
                                    String sourceChannel,
                                    String senderName,
                                    String developmentOwnerUserName,
                                    LocalDateTime receivedAt,
                                    String demandStatus,
                                    String proposerName,
                                    String approvalCode,
                                    String submittedTime,
                                    String requirementType,
                                    String developmentBranchName,
                                    String zentaoUrl,
                                    String requirementDigest,
                                    String department,
                                    String requirementName,
                                    String requirementSummary,
                                    String businessLine,
                                    String remark,
                                    String totalEstimatedEffort,
                                    String developmentEstimatedEffort,
                                    String testingEstimatedEffort,
                                    String plannedDueDate,
                                    String plannedDevelopmentStartDate,
                                    String plannedTestingStartDate,
                                    String plannedReleaseDate,
                                    String developmentStartedDate,
                                    String actualEffort,
                                    String testingStartedDate,
                                    String actualCompletedTime,
                                    String scheduledAcceptanceDate,
                                    String actualTestingEffort,
                                    String actualTestingCompletedDate,
                                    String acceptanceTime,
                                    String releasedTime,
                                    String projectHint,
                                    List<String> involvedSystems,
                                    String enrichmentStatus,
                                    String status,
                                    Long convertedWorkItemId) {

    public IntakeSummaryResponse(Long id,
                                 String sourceType,
                                 String sourceChannel,
                                 String senderName,
                                 String developmentOwnerUserName,
                                 LocalDateTime receivedAt,
                                 String demandStatus,
                                 String proposerName,
                                 String approvalCode,
                                 String submittedTime,
                                 String requirementType,
                                 String requirementDigest,
                                 String department,
                                 String requirementName,
                                 String requirementSummary,
                                 String businessLine,
                                 String remark,
                                 String totalEstimatedEffort,
                                 String developmentEstimatedEffort,
                                 String testingEstimatedEffort,
                                 String plannedDueDate,
                                 String plannedTestingStartDate,
                                 String plannedReleaseDate,
                                 String developmentStartedDate,
                                 String actualEffort,
                                 String testingStartedDate,
                                 String actualCompletedTime,
                                 String scheduledAcceptanceDate,
                                 String actualTestingEffort,
                                 String actualTestingCompletedDate,
                                 String acceptanceTime,
                                 String releasedTime,
                                 String projectHint,
                                 List<String> involvedSystems,
                                 String enrichmentStatus,
                                 String status,
                                 Long convertedWorkItemId) {
        this(
                id,
                sourceType,
                sourceChannel,
                senderName,
                developmentOwnerUserName,
                receivedAt,
                demandStatus,
                proposerName,
                approvalCode,
                submittedTime,
                requirementType,
                null,
                null,
                requirementDigest,
                department,
                requirementName,
                requirementSummary,
                businessLine,
                remark,
                totalEstimatedEffort,
                developmentEstimatedEffort,
                testingEstimatedEffort,
                plannedDueDate,
                null,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                scheduledAcceptanceDate,
                actualTestingEffort,
                actualTestingCompletedDate,
                acceptanceTime,
                releasedTime,
                projectHint,
                involvedSystems,
                enrichmentStatus,
                status,
                convertedWorkItemId
        );
    }
}
