package cn.aslight.workhub.model.intake;

import java.util.List;

/**
 * IntakeStructuredData 模型。
 */
public record IntakeStructuredData(String category,
                                   String approvalTitle,
                                   String proposerName,
                                   String developmentOwnerUserName,
                                   String approvalCode,
                                   String submittedTime,
                                   String requirementType,
                                   String developmentBranchName,
                                   String zentaoUrl,
                                   String requirementDigest,
                                   String requirementName,
                                   String requirementSummary,
                                   String department,
                                   String businessLine,
                                   String businessLineCode,
                                   String remark,
                                   String plannedDueDate,
                                   String plannedDevelopmentStartDate,
                                   String plannedTestingStartDate,
                                   String plannedReleaseDate,
                                   String developmentStartedDate,
                                   String actualEffort,
                                   String testingStartedDate,
                                   String actualCompletedTime,
                                   String scheduledAcceptanceDate,
                                   String actualTestingEffort,
                                   String actualTestingCompletedDate,
                                   String acceptanceTime,
                                   String releasedTime,
                                   String closedTime,
                                   String closeReason,
                                   String projectHint,
                                   List<IntakeStructuredField> fields,
                                   List<IntakeAttachmentSummary> attachmentSummaries,
                                   IntakeSqlDraft sqlDraft) {

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String remark,
                                String plannedDueDate,
                                String plannedDevelopmentStartDate,
                                String plannedTestingStartDate,
                                String plannedReleaseDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String scheduledAcceptanceDate,
                                String actualTestingEffort,
                                String actualTestingCompletedDate,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                null,
                remark,
                plannedDueDate,
                plannedDevelopmentStartDate,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                scheduledAcceptanceDate,
                actualTestingEffort,
                actualTestingCompletedDate,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String businessLineCode,
                                String remark,
                                String plannedDueDate,
                                String plannedDevelopmentStartDate,
                                String plannedTestingStartDate,
                                String plannedReleaseDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                businessLineCode,
                remark,
                plannedDueDate,
                plannedDevelopmentStartDate,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                null,
                null,
                null,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String remark,
                                String plannedDueDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                null,
                remark,
                plannedDueDate,
                null,
                null,
                null,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                null,
                null,
                null,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String remark,
                                String plannedDueDate,
                                String plannedDevelopmentStartDate,
                                String plannedTestingStartDate,
                                String plannedReleaseDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                null,
                remark,
                plannedDueDate,
                plannedDevelopmentStartDate,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                null,
                null,
                null,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String remark,
                                String plannedDueDate,
                                String plannedTestingStartDate,
                                String plannedReleaseDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                null,
                remark,
                plannedDueDate,
                null,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                null,
                null,
                null,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public IntakeStructuredData(String category,
                                String approvalTitle,
                                String proposerName,
                                String developmentOwnerUserName,
                                String approvalCode,
                                String submittedTime,
                                String requirementType,
                                String developmentBranchName,
                                String zentaoUrl,
                                String requirementDigest,
                                String requirementName,
                                String requirementSummary,
                                String department,
                                String businessLine,
                                String remark,
                                String plannedDueDate,
                                String plannedTestingStartDate,
                                String plannedReleaseDate,
                                String developmentStartedDate,
                                String actualEffort,
                                String testingStartedDate,
                                String actualCompletedTime,
                                String scheduledAcceptanceDate,
                                String actualTestingEffort,
                                String actualTestingCompletedDate,
                                String acceptanceTime,
                                String releasedTime,
                                String closedTime,
                                String closeReason,
                                String projectHint,
                                List<IntakeStructuredField> fields,
                                List<IntakeAttachmentSummary> attachmentSummaries,
                                IntakeSqlDraft sqlDraft) {
        this(
                category,
                approvalTitle,
                proposerName,
                developmentOwnerUserName,
                approvalCode,
                submittedTime,
                requirementType,
                developmentBranchName,
                zentaoUrl,
                requirementDigest,
                requirementName,
                requirementSummary,
                department,
                businessLine,
                null,
                remark,
                plannedDueDate,
                null,
                plannedTestingStartDate,
                plannedReleaseDate,
                developmentStartedDate,
                actualEffort,
                testingStartedDate,
                actualCompletedTime,
                scheduledAcceptanceDate,
                actualTestingEffort,
                actualTestingCompletedDate,
                acceptanceTime,
                releasedTime,
                closedTime,
                closeReason,
                projectHint,
                fields,
                attachmentSummaries,
                sqlDraft
        );
    }

    public String requirementNameOrTitle() {
        if (requirementName != null && !requirementName.trim().isEmpty()) {
            return requirementName.trim();
        }
        if (approvalTitle != null && !approvalTitle.trim().isEmpty()) {
            return approvalTitle.trim();
        }
        return null;
    }
}
