package cn.aslight.workhub.model.intake;

import cn.aslight.workhub.model.attachment.AttachmentResponse;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * IntakeDetail 响应模型。
 */
public record IntakeDetailResponse(Long id,
                                   String sourceType,
                                   String sourceChannel,
                                   String externalMessageId,
                                   String senderName,
                                   String developmentOwnerUserName,
                                   LocalDateTime receivedAt,
                                   String demandStatus,
                                   String pausePreviousDemandStatus,
                                   String pauseReason,
                                   LocalDate pauseDate,
                                   String rawContent,
                                   IntakeStructuredData structuredData,
                                   List<String> involvedSystems,
                                   List<IntakeRelatedWorkItemResponse> relatedWorkItems,
                                   List<IntakeHistoryResponse> histories,
                                   String status,
                                   String enrichmentStatus,
                                   String enrichmentErrorSummary,
                                   LocalDateTime enrichmentUpdatedAt,
                                   IntakeAIDraft aiDraft,
                                   List<AttachmentResponse> attachments,
                                   List<IntakeTodoResponse> todos,
                                   Long convertedWorkItemId,
                                   LocalDateTime createdAt,
                                   LocalDateTime updatedAt) {

    public IntakeDetailResponse(Long id,
                                String sourceType,
                                String sourceChannel,
                                String externalMessageId,
                                String senderName,
                                String developmentOwnerUserName,
                                LocalDateTime receivedAt,
                                String demandStatus,
                                String rawContent,
                                IntakeStructuredData structuredData,
                                List<String> involvedSystems,
                                List<IntakeRelatedWorkItemResponse> relatedWorkItems,
                                List<IntakeHistoryResponse> histories,
                                String status,
                                String enrichmentStatus,
                                String enrichmentErrorSummary,
                                LocalDateTime enrichmentUpdatedAt,
                                IntakeAIDraft aiDraft,
                                List<AttachmentResponse> attachments,
                                List<IntakeTodoResponse> todos,
                                Long convertedWorkItemId,
                                LocalDateTime createdAt,
                                LocalDateTime updatedAt) {
        this(
                id,
                sourceType,
                sourceChannel,
                externalMessageId,
                senderName,
                developmentOwnerUserName,
                receivedAt,
                demandStatus,
                null,
                null,
                null,
                rawContent,
                structuredData,
                involvedSystems,
                relatedWorkItems,
                histories,
                status,
                enrichmentStatus,
                enrichmentErrorSummary,
                enrichmentUpdatedAt,
                aiDraft,
                attachments,
                todos,
                convertedWorkItemId,
                createdAt,
                updatedAt
        );
    }

    public IntakeDetailResponse(Long id,
                                String sourceType,
                                String sourceChannel,
                                String externalMessageId,
                                String senderName,
                                String developmentOwnerUserName,
                                LocalDateTime receivedAt,
                                String demandStatus,
                                String rawContent,
                                IntakeStructuredData structuredData,
                                List<String> involvedSystems,
                                List<IntakeRelatedWorkItemResponse> relatedWorkItems,
                                List<IntakeHistoryResponse> histories,
                                String status,
                                String enrichmentStatus,
                                String enrichmentErrorSummary,
                                LocalDateTime enrichmentUpdatedAt,
                                IntakeAIDraft aiDraft,
                                List<AttachmentResponse> attachments,
                                Long convertedWorkItemId,
                                LocalDateTime createdAt,
                                LocalDateTime updatedAt) {
        this(
                id,
                sourceType,
                sourceChannel,
                externalMessageId,
                senderName,
                developmentOwnerUserName,
                receivedAt,
                demandStatus,
                null,
                null,
                null,
                rawContent,
                structuredData,
                involvedSystems,
                relatedWorkItems,
                histories,
                status,
                enrichmentStatus,
                enrichmentErrorSummary,
                enrichmentUpdatedAt,
                aiDraft,
                attachments,
                List.of(),
                convertedWorkItemId,
                createdAt,
                updatedAt
        );
    }

    public IntakeDetailResponse(Long id,
                                String sourceType,
                                String sourceChannel,
                                String externalMessageId,
                                String senderName,
                                String developmentOwnerUserName,
                                LocalDateTime receivedAt,
                                String demandStatus,
                                String rawContent,
                                IntakeStructuredData structuredData,
                                List<String> involvedSystems,
                                List<IntakeHistoryResponse> histories,
                                String status,
                                String enrichmentStatus,
                                String enrichmentErrorSummary,
                                LocalDateTime enrichmentUpdatedAt,
                                IntakeAIDraft aiDraft,
                                List<AttachmentResponse> attachments,
                                Long convertedWorkItemId,
                                LocalDateTime createdAt,
                                LocalDateTime updatedAt) {
        this(
                id,
                sourceType,
                sourceChannel,
                externalMessageId,
                senderName,
                developmentOwnerUserName,
                receivedAt,
                demandStatus,
                null,
                null,
                null,
                rawContent,
                structuredData,
                involvedSystems,
                List.of(),
                histories,
                status,
                enrichmentStatus,
                enrichmentErrorSummary,
                enrichmentUpdatedAt,
                aiDraft,
                attachments,
                List.of(),
                convertedWorkItemId,
                createdAt,
                updatedAt
        );
    }
}
