package cn.aslight.workhub.model.ops;

import java.time.LocalDateTime;
import java.util.List;

public record XxlJobDashboardResponse(Long id,
                                      String monitorKey,
                                      String businessLineCode,
                                      String environmentCode,
                                      String name,
                                      String xxlJobDatabaseName,
                                      String status,
                                      String message,
                                      LocalDateTime checkedAt,
                                      int executorCount,
                                      int jobCount,
                                      int enabledJobCount,
                                      int disabledJobCount,
                                      int triggerCount,
                                      int triggerRunningCount,
                                      int triggerSuccessCount,
                                      int triggerFailedCount,
                                      String reportUpdatedAt,
                                      int failedJobCount,
                                      int failedJobPage,
                                      int failedJobPageSize,
                                      List<XxlJobFailedJobResponse> failedJobs) {

    public XxlJobDashboardResponse(Long id,
                                   String monitorKey,
                                   String businessLineCode,
                                   String environmentCode,
                                   String name,
                                   String xxlJobDatabaseName,
                                   String status,
                                   String message,
                                   LocalDateTime checkedAt,
                                   int executorCount,
                                   int jobCount,
                                   int enabledJobCount,
                                   int disabledJobCount,
                                   int triggerCount,
                                   int triggerRunningCount,
                                   int triggerSuccessCount,
                                   int triggerFailedCount,
                                   String reportUpdatedAt,
                                   int failedJobCount,
                                   List<XxlJobFailedJobResponse> failedJobs) {
        this(id,
                monitorKey,
                businessLineCode,
                environmentCode,
                name,
                xxlJobDatabaseName,
                status,
                message,
                checkedAt,
                executorCount,
                jobCount,
                enabledJobCount,
                disabledJobCount,
                triggerCount,
                triggerRunningCount,
                triggerSuccessCount,
                triggerFailedCount,
                reportUpdatedAt,
                failedJobCount,
                1,
                failedJobs == null ? 0 : failedJobs.size(),
                failedJobs);
    }
}
