CREATE TABLE `ops_system_alert_cleanup_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(64) NOT NULL,
  `message_keyword` VARCHAR(200) NOT NULL,
  `business_line_code` VARCHAR(128) NULL,
  `environment_code` VARCHAR(64) NULL,
  `service_name` VARCHAR(128) NULL,
  `log_level` VARCHAR(32) NULL,
  `event_category` VARCHAR(32) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL,
  `rule_id` BIGINT NULL,
  `max_event_id` BIGINT NOT NULL DEFAULT 0,
  `processed_event_id` BIGINT NOT NULL DEFAULT 0,
  `deleted_event_count` BIGINT NOT NULL DEFAULT 0,
  `deleted_notification_count` BIGINT NOT NULL DEFAULT 0,
  `operator_user_name` VARCHAR(64) NOT NULL,
  `request_ip` VARCHAR(64) NULL,
  `error_message` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ops_system_alert_cleanup_task_no` (`task_no`),
  KEY `idx_ops_system_alert_cleanup_task_status_time` (`status`, `created_at`),
  KEY `idx_ops_system_alert_cleanup_task_operator_time` (`operator_user_name`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
